/* eslint-disable react/prop-types */
import './Content.css';
import modelImage from './assets/models.jpg';
import datasetImage1 from './assets/figure-1.jpg';
import datasetImage2 from './assets/figure-2.jpg';
import PredictForm from './Upload';

const Content = ({ selectedContent }) => {
    switch (selectedContent) {
        case 'Abstract':
            return (
                <div className="content-container">
                    <ul>
                        <li>Breast cancer remains a significant global health issue among women, with early detection being crucial for successful treatment and improved survival rates.</li>
                        <li>This study introduces a non-invasive method for early breast cancer detection using thermal imaging combined with Explainable Artificial Intelligence (XAI) technique.</li>
                        <li>Thermal imaging, a radiation-free and comfortable alternative to mammography, leverages the heat generated by cancerous tissues due to their higher metabolic activity.</li>
                        <li>XAI techniques, specifically LIME (Local Interpretable Model Agnostic Explanations), were employed to enhance model interpretability and trust by identifying regions in the images indicative of abnormalities.</li>
                        <li>The method was evaluated for its precision, sensitivity, and specificity, demonstrating promising results in accurately detecting early breast cancer signs.</li>
                        <li>The best model was VGG19 with an accuracy of 95.2%, which subsequently helped yield comprehensive explanations.</li>
                        <li>The explanation was consequently used for validating the reliability of the predictions made by YOLOv8 to find the abnormal contour.</li>
                        <li>This approach offers a promising alternative to mammography, combining the comfort and safety of thermal imaging with advanced XAI techniques to improve early breast cancer detection accuracy.</li>
                        <li>The findings present new avenues for further research and validation, potentially revolutionizing breast cancer screening practices.</li>
                    </ul>
                </div>
            );
        case 'Dataset':
            return (
                <div className="content-container">
                    <p>
                        The dataset was obtained from Thermal Images for Breast Cancer Diagnosis DMR-IR (kaggle.com).
                        The grayscale image was normalized to the range [0,1] and then converted into a heatmap using a colormap.
                        This transformation visually enhances the intensity variations in the image, facilitating better interpretation of the data.
                        The obtained data consisted of 89 Normal images and 76 Abnormal images.
                        This research aims at providing a diagnosis tool which is very robust and reliable to all forms of thermograms.
                        Traditional augmentation techniques like rotation, shearing were applied on the images to increase the size of each class for training the models.
                        Figure 1 shows the normal and abnormal heatmaps.
                    </p>
                    <div className="dataset-images">
                        <div className="image-container">
                            <img src={datasetImage1} alt="Abnormal Heatmap" />
                            <p>Abnormal Heatmap</p>
                        </div>
                        <div className="image-container">
                            <img src={datasetImage2} alt="Normal Heatmap" />
                            <p>Normal Heatmap</p>
                        </div>
                    </div>
                </div>
            );
        case 'Models':
            return (
                <>
                    <div className="content-container">
                        <img src={modelImage} alt="Model" className="model-image" />
                        <ul className="key-points-list">
                            <li>
                                <strong>Complexity Boosts Performance:</strong> Increasing model complexity (from CNN to VGG-19) generally enhances performance across various metrics, with VGG-19 showing the best results.
                            </li>
                            <li>
                                <strong>YOLOv8’s Performance Decline:</strong> YOLOv8, despite its complexity, exhibits decreased performance compared to VGG-19, indicating potential overfitting issues.
                            </li>
                            <li>
                                <strong>Recall Tradeoff:</strong> VGG-16 outperforms VGG-19 in Recall by 4.75, suggesting that higher complexity does not always improve the model’s ability to identify all relevant examples.
                            </li>
                            <li>
                                <strong>Precision Issues:</strong> Precision improves with complexity up to VGG-19 but drops with YOLOv8, indicating increased false-positive predictions.
                            </li>
                            <li>
                                <strong>F1-Score and AUC Trends:</strong> Both metrics improve up to VGG-19 but decline with YOLOv8, showing a loss in balancing Recall and Precision and reduced class distinction.
                            </li>
                        </ul>

                    </div>
                </>
            );
        case 'Upload':
            return <div className="content-container"><PredictForm /> </div>;
        default:
            return <div className="content-container"><p>Select a menu item.</p></div>;
    }
};

export default Content;